Test TUH classes
braindecode/braindecode pull request #276
Opened 2021-06-24 10:27 UTC by gemeinl

2021-06-24 10:31 UTC, gemeinl commented
I am thinking to also add this kind of mocking to the `tuh_eeg_corpus.py` example, such that it can be automatically run by CI / docs. This would ensure that there are no bugs in the example.
Are there any objections regarding this or support this idea @agramfort @robintibor @hubertjb @sliwy ?

2021-06-24 11:38 UTC, robintibor commented
wow looks superprofessional to me

2021-06-24 11:38 UTC, robintibor approved these changes

2021-06-24 11:39 UTC, robintibor commented
really impressive

2021-06-24 12:11 UTC, agramfort approved these changes
nice !

2021-06-24 12:35 UTC, robintibor commented
Please mark [WIP] or [MRG] depending on what you want @gemeinl

2021-06-24 16:04 UTC, gemeinl commented
Done from my side although the docs seem to have died somewhere during this PR...

2021-06-24 16:54 UTC, robintibor requested changes

2021-06-24 16:54 UTC, robintibor commented on examples/plot_tuh_eeg_corpus.py
> +ax.set_xlabel('Count')
```suggestion
ax.set_ylabel('Count')
```

Mistake in axis label...

2021-06-24 20:29 UTC, gemeinl commented
List in https://github.com/braindecode/braindecode/pull/276/files#diff-60801eb2489f88511279735603d520c5d613d4daa1f6a9630d0b681830cf72beR197-R203 still does not look as intended. Apart from this finally done.

2021-06-24 21:02 UTC, robintibor commented on examples/plot_tuh_eeg_corpus.py
> +# #. crop the recordings to a region of interest
```suggestion
#
# #. crop the recordings to a region of interest
```

2021-06-24 21:16 UTC, robintibor approved these changes

2021-06-24 21:17 UTC, merged

2021-06-24 21:17 UTC, robintibor commented
So you needed to add one line only with:
 `#`
right before the list for everything to work @gemeinl 
Thanks for the great work, merged!

2021-06-25 08:11 UTC, gemeinl commented
Ah, I see. Same mistakes over and over again...
Thanks for fixing!