transfer learning
braindecode/braindecode pull request #580
Opened 2024-03-26 20:42 UTC by MohammadJavadD

2024-03-28 16:10 UTC, MohammadJavadD commented
We also have added the code to download and prepare both datasets (TUAB and NMT) and then training and fine-tuning steps. the code works with the newest TUAB dataset and Braindecode. Please let me know if you have any questions. [APD_EEG repo](https://github.com/MohammadJavadD/APD_EEG).

2024-03-28 17:28 UTC, bruAristimunha commented
Yes, @MohammadJavadD, you read my mind. this is my block with this PR and the NMT dataset PR. I am thinking of something....

2024-04-14 19:14 UTC, bruAristimunha requested changes, later dismissed
Hi @MohammadJavadD,

I made a rapid initial review. We need a little more text/concepts and some figures. Maybe put a static figure from your paper or my paper.

Can you work a little on the text that comments?

2024-04-14 19:14 UTC, bruAristimunha commented on examples/advanced_training/transfer_learning.py
> +# Here we assume you already load and preprocess the raw recordings for both TUAB and NMT datasetsand saved the file in `TUAB_path' and 'NMT_path' respectively. To read more see this notebook [here](
```suggestion
# Here, we assume you have already loaded and preprocessed the raw recordings for both TUAB and NMT datasets and saved the file in `TUAB_path` and `NMT_path` respectively. To read more, see how to load the Temple University Dataset in this braindecode [tutorial](https://braindecode.org/stable/auto_examples/applied_examples/plot_tuh_eeg_corpus.html)
```

2024-04-14 19:14 UTC, bruAristimunha commented on examples/advanced_training/transfer_learning.py
> +# -------------------------------------
The concept of target needs to be clear at the begin of the tutorial.

2024-04-14 19:14 UTC, bruAristimunha commented on examples/advanced_training/transfer_learning.py
> +# split based on train split from dataset
Explain a little more about the true and false here, related with abnormal classification

2024-04-14 19:14 UTC, bruAristimunha commented on examples/advanced_training/transfer_learning.py
> +# In this tutorial, we use DeepNet introduced in [4].
Can you discuss a little more about the choice of the parameters?

2024-04-14 19:14 UTC, bruAristimunha commented on examples/advanced_training/transfer_learning.py
> +# In this tutorial, we use DeepNet introduced in [4].
You can directly use your paper, and say something, as investigated in [1] ...

2024-04-14 19:14 UTC, bruAristimunha commented on examples/advanced_training/transfer_learning.py
> +)
```suggestion
print(clf)
```
This is will print the parameters because of EEGClassifier

2024-04-14 19:14 UTC, bruAristimunha commented on examples/advanced_training/transfer_learning.py
> +)
```suggestion
print(clf)
```

2024-04-14 19:14 UTC, bruAristimunha commented on examples/advanced_training/transfer_learning.py
> +
You can put more information about why this is important and things like this

2026-08-24 22:05 UTC, merged