Lazy index for fixed length windower
braindecode/braindecode pull request #597
Opened 2024-04-24 16:48 UTC by PierreGtch

This adds the option to use lazily compute the trial bounds when using `create_fixed_length_windows`.

Useful when working with small strides that can lead to metadata DataFrames nearly the same size as the dataset itself.

2024-05-08 12:13 UTC, bruAristimunha commented
@robintibor, can you review this modification on temple university dataset?

2024-05-21 10:30 UTC, bruAristimunha requested changes
very small comments, but lgtm

2024-05-21 11:42 UTC, PierreGtch commented on braindecode/preprocessing/windowers.py
> +    lazy_metadata: bool
This argument should only be a bool, not None

2024-05-21 11:43 UTC, PierreGtch commented
Thanks @bruAristimunha for the comments! :)

2024-05-21 12:31 UTC, bruAristimunha approved these changes

2024-05-21 12:31 UTC, merged

2024-05-21 12:32 UTC, bruAristimunha commented
Thank you @PierreGtch =)