[EHN] Including CTNet into braindecode
braindecode/braindecode pull request #666
Opened 2024-10-07 20:39 UTC by bruAristimunha

This model is very interesting! It is a natural evolution of the EEGConformer, published in Scientific Rep. I finished the adaptation for braindecode, but the review by the authors needs to be done.

@eeyhsong and @snailpt  can you review?

2024-10-08 13:21 UTC, bruAristimunha commented
Hey @snailpt,

Great that the re-implementation is correct! Thank you so much for your time.

When this PR is integrated, your model will be integrated into the braindecode source; you can use [installing braindecode from the source](https://braindecode.org/stable/install/install_source.html#installing-braindecode-from-the-source), and in our next release, which will be coming soon, you will be able to use it with `pip install braindecode.`

About braindecode.

We are particularly interested in your view of being a new user. We are currently expanding the zoo model, but we have several features, such as data augmentation, self-supervised, and an IO well integrated with mne, for example.

Your contribution as someone new in Github can be either reviewing the documentation, opening an issue indicating things that are not clear, or even integrating things that you think are necessary, such as a new data augmentation, and interpretability.
In my experience, things that can help your research usually lead to more interesting new features.

I sincerely appreciate any time you can dedicate to the library! I think together we can go further!

2024-10-08 19:59 UTC, bruAristimunha commented
Missing adjust in the api.rst file

2024-10-09 13:47 UTC, bruAristimunha commented
Executing some cross-session training in the competition dataset, I have these results:

![image](https://github.com/user-attachments/assets/7bdef832-b39c-49de-a854-65597afc825b)
![image](https://github.com/user-attachments/assets/dfd08602-b0c3-4794-a7d9-806d18f43014)

I used moabb, so the pre-processing is different, and there is no data augmentation.

I will test the impact of the position encoding, I remember that for the EEG conformer it does not contribute much

2024-10-09 20:35 UTC, bruAristimunha commented on braindecode/models/ctnet.py
> +    TODO: fill here..
Can you fill here @snailpt?

You will need to suggest.

2024-10-09 20:35 UTC, bruAristimunha commented on braindecode/models/ctnet.py
> +    [ctnetcode]_ to comply with Braindecode's model standards. More comments.
```suggestion
    [ctnetcode]_ to comply with Braindecode's model standards. More comments.
```

and here too

2024-10-10 00:49 UTC, bruAristimunha commented on docs/whats_new.rst
> +- Adding :class:`braindecode.models.CTNet`  (:gh:`640` by `Bruno Aristimunha`_ )
```suggestion
- Adding :class:`braindecode.models.CTNet`  (:gh:`666` by `Bruno Aristimunha`_ )
```

2024-10-10 07:41 UTC, snailpt commented
I have already added the corresponding suggestions and comments in the code. Why is the status of my responses still showing as 'pending' in the conversation?

2024-10-10 08:05 UTC, bruAristimunha commented
Hey @snailpt,

GitHub is a bit confusing sometimes, you will need to go to the review page again and submit your review @snailpt. 

I think it's a green button at the top of the page.

2024-10-10 08:21 UTC, snailpt commented
Hey @bruAristimunha   This is no longer important. Could you please check if I have filled in everything required from my side?

2024-10-10 08:25 UTC, bruAristimunha commented
Unfortunately I can't see it, only the person who started the review can see the draft. 

Here is a tutorial that may help you: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request

2024-10-10 08:29 UTC, snailpt commented
I finally found the submit button! If there’s anything else I can assist with, please feel free to let me know.

2024-10-10 12:45 UTC, elouayas requested changes
The model's inference works well, and I tested it across various scenarios.

I only noticed a small limitation when the input time signal duration is too long. This issue arises from the way the positional encoding is implemented.

Currently, the positional encoding is defined as a fixed parameter with a specified length, which defaults to 100:

`self.encoding = nn.Parameter(torch.randn(1, length, emb_size))`

During the forward pass, only the relevant portion of this encoding (determined by seq_length) is used by indexing the elements.

If the input signal is too long, the length parameter must be manually increased to satisfy the following condition:

`int(n_times / (pool_size_1 * pool_size_2)) > length`

With the default values in the code:

`int(n_times / (8 * 8)) > 100`

With the default values, it means that if n_times (the signal's time duration) exceeds 6463, the inference will crash.

For BCI applications, 6463 should generally be sufficient, given their typical duration and sampling rates. However, it would be beneficial to make the code more flexible.

To address this, the length could be automatically determined based on the input tensor size during the forward pass by calculating:

`length = int(n_times / (pool_size_1 * pool_size_1))`
This adjustment would improve the model's adaptability to different signal lengths.

2024-10-12 00:18 UTC, snailpt commented
@bruAristimunha I have tested on the BCI IV-2a and 2b datasets, and found that not applying band-pass filtering to the raw EEG during CTNet data preprocessing yields better results. And looking forward to comparing the experimental results after using S&R data augmentation.

2024-10-12 00:21 UTC, snailpt commented
> Executing some cross-session training in the competition dataset, I have these results:
> 
> ![image](https://private-user-images.githubusercontent.com/42702466/374966865-7bdef832-b39c-49de-a854-65597afc825b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTIzNzMsIm5iZiI6MTcyODY5MjA3MywicGF0aCI6Ii80MjcwMjQ2Ni8zNzQ5NjY4NjUtN2JkZWY4MzItYjM5Yy00OWRlLWE4NTQtNjU1OTdhZmM4MjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDAwMTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YWRkMDA4ZjhkMDAwZmIxMGIxOGYxZWJhZjZiYzQ1ZmQxODM5ODJlYWI2ZWNkZjU1ZWU4YTA2OGRiMWZlZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rzsALNYqMfdEnbwmlIqAHHp0o0sa7j-rgpXsE30DNEQ) ![image](https://private-user-images.githubusercontent.com/42702466/374966912-dfd08602-b0c3-4794-a7d9-806d18f43014.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTIzNzMsIm5iZiI6MTcyODY5MjA3MywicGF0aCI6Ii80MjcwMjQ2Ni8zNzQ5NjY5MTItZGZkMDg2MDItYjBjMy00Nzk0LWE3ZDktODA2ZDE4ZjQzMDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDAwMTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MzAzOTBjNzQxNzY3Yjg4MDQyMzAzZTBkMzg1YmQ4ZjE0NjUwMTAyYzI4ODZjYTk3ZjNiYmFkZjZlYzY5MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A0nZyhq-X33irII3izclY1lhGkC-2dTq82_Y0EPw4GQ)
> 
> I used moabb, so the pre-processing is different, and there is no data augmentation.
> 
> I will test the impact of the position encoding, I remember that for the EEG conformer it does not contribute much

I have tested on the BCI IV-2a and 2b datasets, and found that not applying band-pass filtering to the raw EEG during CTNet data preprocessing yields better results. And looking forward to comparing the experimental results after using S&R data augmentation.

2024-10-15 09:36 UTC, merged