[MNT] Eegnetv4 fix v2
braindecode/braindecode pull request #680
Opened 2024-10-22 13:05 UTC by bruAristimunha

2025-02-04 09:10 UTC, bruAristimunha commented
The benchmark table @tomMoral 
![image](https://github.com/user-attachments/assets/8278d450-5540-4369-aad8-2d76f6322ee9)
![image](https://github.com/user-attachments/assets/945717eb-a9c4-4149-acb0-1614fd55b84e)
![image](https://github.com/user-attachments/assets/3aebb264-b4b0-47d7-9b84-a6807a22d43e)

2025-02-05 15:05 UTC, bruAristimunha commented
Hey @tomMoral,

I did a more in-depth study for EEGNet because the benchmark I initially did was slightly different from the original result. (different evaluation)

In the original article, we have interfered from the barplot that the accuracy is 68% +-[70%-67%] (Within-Subject, mixing two sessions and doing cross-validation with four folds (conceptually wrong for me)) and 38% +- [42%-35%] (inter-subjects).

Using benchopt, I investigated the impact of different band frequencies (one of the key differences following our table):
![intra_session](https://github.com/user-attachments/assets/44b6a69f-fb23-4415-aaa0-54f21d7bb90f)
![inter_session](https://github.com/user-attachments/assets/3117b703-44e4-4567-89ef-167d1d41aeff)
![inter_subject](https://github.com/user-attachments/assets/da4e37a7-33be-4b81-90a3-f7c1b5ae3d71)


Using only the closest frequency range [4Hz, 38Hz], we have better results.
| objective_name   | use_linear_layer=False   | use_linear_layer=True   |   original             |
|:-----------------|:-------------------------|:------------------------|:------------------------|
| inter_sessions   | 44.5+-19.96              | 59.38+-15.63            |          |
| inter_subjects   | 51.15+-6.31              | 49.31+-8.51             | 38% +- [42%-35%]         |
| intra_session    | 47.09+-23.21             | 62.87+-20.77            |              |
| within session   |    -                              |                                  | 68% +-[70%-67%]   |


There are several interesting things about this contrast of different evaluations, more or less filtering and domain generalization, and possibly, because of this, the implementation has not been corrected before. Since linear is better when we filter less, I will keep it in my ideas box to explore in the future, somewhat along the lines of our article in the CNS.

We should integrate this code that adds this parameter, and during the benchmark, we validate whether we leave it as linear as default or not.

2025-02-22 21:59 UTC, PierreGtch requested changes
Nice job @bruAristimunha !! I'm just not sure about the parameter name and the default. WDYT?

2025-02-22 21:59 UTC, PierreGtch commented on braindecode/models/eegnet.py
> +                    in_features=output_shape[1] * output_shape[3],
```suggestion
                    in_features=self.F2 * self.final_conv_length,
```
(For consistency with the convolutional layer version)

Plus, in case `n_out_virtual_chans!=1`, it doesn't work. Is it possible to be in this case?
- If yes, we need `in_features=self.F2 * n_out_virtual_chans  * self.final_conv_length`
- Otherwise, we should replace `n_out_virtual_chans` everywere to simplify the code and put an `assert output_shape[2]==1`

2025-02-22 21:59 UTC, PierreGtch commented on braindecode/models/modules.py
> +                self.weight.data, p=2, dim=0, maxnorm=self.max_norm
I think this is correct but not trivial because there is a double inversion between pytorch and tensorflow!
- In torch, the kernel has shape `(out_features, in_features)` and it's the oposite in tensorflow.
- In tensorflow the `axis` parameter of `max_norm`specifies the dim along which the norm is computed, whereas the `dim` parameter of `torch.renorm` specifies the dim along which the sub-tensors are split

I checked just to be sure and it seem correct:
```python
>>> kernel = tf.constant([[0.0,1,2],[3,4,5]])
>>> tf.keras.constraints.max_norm(max_value=2)(kernel)
<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.        , 0.48507127, 0.74278134],
       [2.        , 1.9402851 , 1.8569534 ]], dtype=float32)>
```
(see [original EEGNet implementation](https://github.com/vlawhern/arl-eegmodels/blob/4a512e503198db2010848813ead9afbf8cd54c97/EEGModels.py#L152))
```python
>>> kernel = torch.tensor([[0.0,1,2],[3,4,5]]).T # we transpose because the kernel is transposed in torch
>>> torch.renorm(kernel, p=2, dim=0, maxnorm=2)
tensor([[0.0000, 2.0000],
        [0.4851, 1.9403],
        [0.7428, 1.8570]])
```

2025-02-22 21:59 UTC, PierreGtch commented on braindecode/models/eegnet.py
> +        apply a flattened linear layer as the final classification step.
```suggestion
    final_layer_with_constraint : bool, default=False
        If ``False``, uses a convolution-based classification layer. If ``True``,
        apply a flattened linear layer with constraint on the weights norm as the final classification step.
```
The fact that it's linear vs. convolutional is not super important, the main difference is the constraint. So I think the name should reflect that

2025-02-22 21:59 UTC, PierreGtch commented on braindecode/models/eegnet.py
> +        final_layer_linear: bool = False,
Should we use the "correct" EEGNet implementation as default instead? 
Or maybe a deprecation warning in case `final_layer_linear=False` to say that this is not the correct implementation and that the default value will change in the future

2025-02-24 10:03 UTC, bruAristimunha commented on braindecode/models/eegnet.py
> +        final_layer_linear: bool = False,
```suggestion
        final_layer_with_constraint: bool = False,
```

2025-02-24 10:03 UTC, bruAristimunha commented on braindecode/models/eegnet.py
> +        if not final_layer_linear:
```suggestion
        if not final_layer_with_constraint:
```

2025-02-24 10:03 UTC, bruAristimunha commented on braindecode/models/eegnet.py
> +                "Parameter 'final_layer_linear=False' is deprecated and will be "
```suggestion
                "Parameter 'final_layer_with_constraint=False' is deprecated and will be "
```

2025-02-25 09:15 UTC, bruAristimunha commented
Hi @PierreGtch  and @tomMoral,

I appreciate your review @PierreGtch. I have incorporated everything. I really like the new name, thank you for that. As for changing the name, I would rather not. Let's wait for a release to do that.

2025-02-26 17:05 UTC, sylvchev commented
Thanks @bruAristimunha !

2025-02-26 17:07 UTC, merged